name: ET
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - aiofiles
  - aiosqlite
  - alsa-lib
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow
  - asttokens
  - attr
  - attrs
  - babel
  - backcall
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  - bleach
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - ca-certificates
  - cached-property
  - cached_property
  - cairo
  - certifi
  - cffi
  - charset-normalizer
  - comm
  - contourpy
  - cycler
  - dbus
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - exceptiongroup
  - executing
  - expat
  - flit-core
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - fqdn
  - freetype
  - gettext
  - glib
  - glib-tools
  - gmp
  - gmpy2
  - graphite2
  - gst-plugins-base
  - gstreamer
  - harfbuzz
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - ipykernel
  - ipython
  - ipython_genutils
  - isoduration
  - jedi
  - jinja2
  - json5
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jsonschema-with-format-nongpl
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_fileid
  - jupyter_server_terminals
  - jupyter_server_ydoc
  - jupyter_ydoc
  - jupyterlab
  - jupyterlab-markup
  - jupyterlab_pygments
  - jupyterlab_server
  - keyutils
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcap
  - libcblas
  - libclang
  - libclang13
  - libcups
  - libdeflate
  - libedit
  - libevent
  - libexpat
  - libffi
  - libflac
  - libgcc-ng
  - libgcrypt
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libgomp
  - libgpg-error
  - libiconv
  - libjpeg-turbo
  - liblapack
  - libllvm15
  - libnsl
  - libogg
  - libopenblas
  - libopus
  - libpng
  - libpq
  - libsndfile
  - libsodium
  - libsqlite
  - libstdcxx-ng
  - libsystemd0
  - libtiff
  - libuuid
  - libvorbis
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libzlib
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mpc
  - mpfr
  - mpg123
  - mpmath
  - munkres
  - mysql-common
  - mysql-libs
  - nbclassic
  - nbclient
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - nbformat
  - ncurses
  - nest-asyncio
  - notebook
  - notebook-shim
  - nspr
  - nss
  - numpy
  - openjpeg
  - openssl
  - overrides
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - patsy
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - pkgutil-resolve-name
  - platformdirs
  - ply
  - pooch
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pulseaudio-client
  - pure_eval
  - pycparser
  - pygments
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python-tzdata
  - python_abi
  - pytz
  - pyyaml
  - pyzmq
  - qt-main
  - readline
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rpds-py
  - scipy
  - seaborn
  - seaborn-base
  - send2trash
  - setuptools
  - sip
  - six
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - statsmodels
  - sympy
  - terminado
  - tinycss2
  - tk
  - toml
  - tomli
  - tornado
  - traitlets
  - typing-extensions
  - typing_extensions
  - typing_utils
  - tzdata
  - uri-template
  - urllib3
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - wheel
  - xcb-util
  - xcb-util-image
  - xcb-util-keysyms
  - xcb-util-renderutil
  - xcb-util-wm
  - xkeyboard-config
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xf86vidmodeproto
  - xorg-xproto
  - xz
  - y-py
  - yaml
  - ypy-websocket
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
      - ipython-tikzmagic
